### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by henricavalcante** [mashpie/i18n-node#158]
```
npm test

> i18n@0.5.0 test /Users/henricavalcante/git/maisquestoes/api/node_modules/i18n
> make test

mocha --reporter spec
/Users/henricavalcante/git/maisquestoes/api/node_modules/mocha/lib/utils.js:591
      if (!files.length) throw new Error("cannot resolve path (or pattern) '"
                               ^
Error: cannot resolve path (or pattern) 'test'
    at Object.lookupFiles (/Users/henricavalcante/git/maisquestoes/api/node_modules/mocha/lib/utils.js:591:32)
    at /Users/henricavalcante/git/maisquestoes/api/node_modules/mocha/bin/_mocha:320:30
    at Array.forEach (native)
    at Object.<anonymous> (/Users/henricavalcante/git/maisquestoes/api/node_modules/mocha/bin/_mocha:319:6)
    at Module._compile (module.js:431:26)
    at Object.Module._extensions..js (module.js:449:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:472:10)
    at startup (node.js:124:18)
    at node.js:959:3
make: *** [test] Error 1
npm ERR! Test failed.  See above for more details.
```

**Comment by mashpie** [comment]
https://travis-ci.org/mashpie/i18n-node

**Comment by henricavalcante** [comment]
what about iojs?

**Comment by henricavalcante** [comment]
```
> i18n@0.5.0 test /Users/henricavalcante/git/i18n-node
> make test

mocha --reporter spec


  Module Setup
    ✓ should export a valid version
    ✓ should export configure as i18nConfigure
    ✓ should export init as i18nInit
    ✓ should export __ as i18nTranslate
    ✓ should export __n as i18nTranslatePlural
    ✓ should export setLocale as i18nSetLocale
    ✓ should export getLocale as i18nGetLocale
    ✓ should export getCatalog as i18nGetCatalog

  Module API
    Global Scope
      i18nSetLocale and i18nGetLocale
        ✓ getLocale should return default setting
        ✓ setLocale should return the new setting
        ✓ and getLocale should return the new setting
      i18nGetCatalog
        ✓ should return all catalogs when invoked with empty parameters
        ✓ should return just the DE catalog when invoked with "de" as parameter
        ✓ should return just the EN catalog when invoked with "en" as parameter
        ✓ should return false when invoked with unsupported locale as parameter
      i18nTranslate
        ✓ should return en translations as expected
        ✓ should return en translations as expected, using mustached messages
        ✓ should return de translations as expected
        ✓ should return de translations as expected, using mustached messages
        ✓ should also return translations when iterating thru variables values
        ✓ should be possible to use an json object as 1st parameter to specifiy a certain locale for that lookup
      i18nTranslatePlural
        ✓ should return singular or plural form based on last parameter
        ✓ should return substituted phrases when used nested
        ✓ won't return substitutions when not masked by an extra % (%% issue #49)
        ✓ should be possible to use an json object as 1st parameter to specifiy a certain locale for that lookup
    Local Scope
      i18nInit
        ✓ should set language to first-choice language from header when first choice is available
        ✓ should set regional language to first choice from header when first choice is available
        ✓ should set fallback language from header when first choice is not available
        ✓ should set fallback regional language from header when first choice is not available
        ✓ should set fallback language from header when first choice regional language is not available
        ✓ should set default language when no available language is found in header
        ✓ should set default language when an available language is specified with zero quality factor
        ✓ should set correct fallback language when quality factors are specified out of order
        ✓ should set fallback language from regional language when no exact match in header
      Object as parameter
        i18nSetLocale and i18nGetLocale
          ✓ should return the current local setting, when used with 2 args
          ✓ while getLocale should still return the previous global setting
          ✓ now getLocale should return local locale when used with local object as 1st arg
          ✓ should return the default local setting, when used with 2 args and an unsupported local, when req.locale is undefined
        i18nGetCatalog
          ✓ should return the current catalog when invoked with empty parameters
          ✓ should return just the DE catalog when invoked with "de" as parameter
          ✓ should return just the EN catalog when invoked with "en" as parameter
          ✓ should return false when invoked with unsupported locale as parameter
        i18nGetLocales
          ✓ should return the locales
        i18nTranslate
          ✓ has to use local translation in en
          ✓ while the global translation remains untouched
          ✓ and has to use local translation in de
          ✓ still the global translation remains untouched
          ✓ should be possible to use an json object as 1st parameter to specifiy a certain locale for that lookup
      Attached to object
        i18nSetLocale and i18nGetLocale
          ✓ should return the current local setting, when used with 1 arg
          ✓ while getLocale should still return the previous global setting
          ✓ now getLocale should return local locale
        i18nGetCatalog
          ✓ should return the current catalog when invoked with empty parameters
          ✓ should return just the DE catalog when invoked with "de" as parameter
          ✓ should return just the EN catalog when invoked with "en" as parameter
          ✓ should return false when invoked with unsupported locale as parameter
        i18nTranslate
          ✓ has to use local translation in en
          ✓ while the global translation remains untouched
          ✓ and has to use local translation in de
          ✓ still the global translation remains untouched
          ✓ should be possible to use an json object as 1st parameter to specifiy a certain locale for that lookup
      i18nTranslatePlural
        ✓ should return singular or plural form based on last parameter
        ✓ should return substituted phrases when used nested
        ✓ won't return substitutions when not masked by an extra % (%% issue #49)
        ✓ should be possible to use an json object as 1st parameter to specifiy a certain locale for that lookup

  Module Config
    ✓ should be possible to setup a custom directory
    ✓ should be possible to read custom files with custom prefixes and extensions

  Module Defaults
    ✓ should be possible to setup a custom directory
    ✓ should be possible to read custom files with default a extension of .json (issue #16)

  Object Notation
    Date/Time patterns
      ✓ should return en formatting as expected
      ✓ should return de formatting as expected
    i18nTranslate
      ✓ should return en translations as expected, using object traversal notation
      ✓ should provide proper pluralization support, using object traversal notation


  72 passing (125ms)
```
