### ISSUE TITLE
Error: Cannot find module 'sprintf'

### ISSUE THREAD

**Issue by ajbeach2** [mashpie/i18n-node#184]
I am trying to run the express4-cookies example. I run:

```
npm install
node express-cookies.js
```
and i get the following error:

```
module.js:338
    throw err;
          ^
Error: Cannot find module 'sprintf'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/alex.beach/Workspace/i18n-node/i18n.js:10:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by mashpie** [comment]
Did you run npm install inside of examples or in top directory? And do refer to npm version or dev directly via github?

**Comment by ajbeach2** [comment]
I cloned the repo from github, cd'd into the example folder express4
cookies and ran the npm commands to install, the attempted to start the
server.

**Comment by mashpie** [comment]
successfully cloned and started like this:

    $ git clone git@github.com:mashpie/i18n-node.git

    $ cd i18n-node/examples

    $ npm install
    [...]
    sprintf@0.1.5 ../node_modules/sprintf
    mustache@2.2.0 ../node_modules/mustache
    async@1.5.0 ../node_modules/async
    debug@2.2.0 ../node_modules/debug
    └── ms@0.7.1
    [...]

    $ cd express-cookies 
    $ node express-cookies.js

please check your `node_modules` and review output of `npm install`

**Comment by ajbeach2** [comment]
Ah, well npm install inside of the examples directory (and not inside the express4-cookies folder seems have solved the issue.
