### ISSUE TITLE
Plurals not working in files named with national variety (e.g., "en-US", "pt-BR", etc)

### ISSUE THREAD

**Issue by danilotl** [mashpie/i18n-node#231]
Plurals not working in files named with national variety (e.g., "en-US", "pt-BR", etc)

When using plurals **__n()** in files named with national variety, the following error occurs:

    Locale "en-US" cardinal rules not found
       at MakePlural.compile (/home/ubuntu/workspace/node_modules/i18n/node_modules/make-plural/make-plural.js:182:32)
       at compile (/home/ubuntu/workspace/node_modules/i18n/node_modules/make-plural/make-plural.js:214:85)
       at Array.map (native)
       at MakePlural.buildFunction (/home/ubuntu/workspace/node_modules/i18n/node_modules/make-plural/make-plural.js:222:95)
       at new MakePlural (/home/ubuntu/workspace/node_modules/i18n/node_modules/make-plural/make-plural.js:166:24)
       at i18nTranslatePlural (/home/ubuntu/workspace/node_modules/i18n/i18n.js:366:13)
       at eval (eval at <anonymous> (/home/ubuntu/workspace/node_modules/ejs/lib/ejs.js:485:12), <anonymous>:20:23)
       at Template.compile.returnedFn (/home/ubuntu/workspace/node_modules/ejs/lib/ejs.js:514:17)
       at View.exports.renderFile [as engine] (/home/ubuntu/workspace/node_modules/ejs/lib/ejs.js:358:31)
       at View.render (/home/ubuntu/workspace/node_modules/express/lib/view.js:126:8)

Example of working file (without plurals):

**en-US.json**

    {
        "hello_world": "Hello, world!"
    }

Example of non-working file (with plurals):

**en-US.json**

    {
        "hello_world": "Hello, world!",
        "%s cats": {
            "one": "%s cat",
            "other": "%s cats"
        }
    }

Using the following code to print the text in an EJS template file:

    <p> <%= __n('%s cats', 2) %> </p>

If you rename the file just to **en.json** (same content), it works.

I'm using the `app.use(i18n.init);` in Express to determine the locale based on the browser settings.

**Comment by mashpie** [comment]
Ok, I think I see the problem. First off: The stack trace starts in the underlying module `make-plural`. As far as I can see right now, make-plural is not aware of country- or region-codes and only handles languages (https://github.com/eemeli/make-plural.js).

So, stripping the region in i18n for fetching plural rules should fix that (at around https://github.com/mashpie/i18n-node/blob/master/i18n.js#L358).

I guess the same error occurs to messageFormat (https://github.com/mashpie/i18n-node#i18n__mf) - did you try that already?

A workaround might also be to use ranges (https://github.com/mashpie/i18n-node#ranged-interval-support), like so:

```js
{
    "%s cats": "[0] no cat|[1] one cat|[2,] %s cats"
}
```

Have you tried that? Or, you might omit the region in your settings, so "pt-BR" and "pt-PT" both refer to "pt".

I will add a regression in the meantime to address locales with regions in depth.

**Comment by danilotl** [comment]
I didn't try to use the messageFormat yet... And I just tried to use ranges and it works, so I'll be using it for now. Thank you for the workaround!

And I don't have a "pt-PT" yet, so I can also rename it to just "pt" to make it work. But I know that "pt-BR" and "pt-PT" have considerable differences, so it might come to a point where I will need to have both. But for now, the ranges do the work :+1:
