### ISSUE TITLE
Cannot set property 'locale' of undefined

### ISSUE THREAD

**Issue by goowikns** [mashpie/i18n-node#238]
I get following error:
```
Cannot set property 'locale' of undefined
TypeError: Cannot set property 'locale' of undefined
    at Object.i18nSetLocale [as setLocale] (C:\Users\...\project\node_modules\i18n\i18n.js:404:25)
    at C:\Users\...\project\app.js:67:10
    at Layer.handle [as handle_request] (C:\Users\...\project\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\...\project\node_modules\express\lib\router\index.js:312:13)
    at C:\Users\...\project\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (C:\Users\...\project\node_modules\express\lib\router\index.js:330:12)
    at next (C:\Users\...\project\node_modules\express\lib\router\index.js:271:10)
    at i18nInit (C:\Users\...\project\node_modules\i18n\i18n.js:201:14)
    at Layer.handle [as handle_request] (C:\Users\...\project\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\...\project\node_modules\express\lib\router\index.js:312:13)
    at C:\Users\...\project\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (C:\Users\...\project\node_modules\express\lib\router\index.js:330:12)
    at next (C:\Users\...\project\node_modules\express\lib\router\index.js:271:10)
    at SendStream.error (C:\Users\...\project\node_modules\express\node_modules\serve-static\index.js:120:7)
    at emitOne (events.js:77:13)
    at SendStream.emit (events.js:169:7)
    at SendStream.error (C:\Users\...\project\node_modules\express\node_modules\send\index.js:245:17)
    at SendStream.onStatError (C:\Users\...\project\node_modules\express\node_modules\send\index.js:356:12)
    at next (C:\Users\...\project\node_modules\express\node_modules\send\index.js:658:28)
    at C:\Users\...\project\node_modules\express\node_modules\send\index.js:666:23
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Here is my code:**

```
i18n.configure({
  locales: ['nl', 'fr'],
  register: global,
  cookie: 'gmlang',
  directory: __dirname + '/locales',
  defaultLocale: 'nl'
});

app.use(i18n.init);

app.use(function (req, res, next) {
  console.log(i18n);
  if (req.query.lang != undefined && i18n.locales.indexOf(req.query.lang) >= 0) {
    i18n.setLocale(req.query.lang);
  }else{
    i18n.setLocale(i18n.defaultLocale);
  }
  next();
});
```

When logging the i18n I also get an empty locales object:
```
{ locales: {},
  version: '0.8.2',
  configure: [Function: i18nConfigure],
  init: [Function: i18nInit],
  __: [Function: i18nTranslate],
  __mf: [Function: i18nMessageformat],
  __l: [Function: i18nTranslationList],
  __h: [Function: i18nTranslationHash],
  __n: [Function: i18nTranslatePlural],
  setLocale: [Function: i18nSetLocale],
  getLocale: [Function: i18nGetLocale],
  getCatalog: [Function: i18nGetCatalog],
  getLocales: [Function: i18nGetLocales],
  addLocale: [Function: i18nAddLocale],
  removeLocale: [Function: i18nRemoveLocale] }
```

Any ideas?

**Comment by mashpie** [comment]
First off: Don't use i18n globally in context of web requests! It won't work as you'll run into concurrency issues.

My guess from your code is wrong usage of `setLocale`. Examples (@see https://github.com/mashpie/i18n-node#i18nsetlocale):

```js
i18n.setLocale(req, 'ar'); // --> req: مرحبا res: مرحبا res.locals: مرحبا
i18n.setLocale(res, 'ar'); // --> req: Hallo res: مرحبا res.locals: مرحبا
i18n.setLocale(res.locals, 'ar'); // --> req: Hallo res: Hallo res.locals: مرحبا
```

**Comment by mashpie** [comment]
consider that example (as far as I can guess your use case from your code):

```js
i18n.configure({
  locales: ['nl', 'fr'],
  // register: global, <-- never use global scope in web requests
  cookie: 'gmlang',
  queryParameter: 'lang', // query parameter to switch locale (ie. /home?lang=nl) - defaults to NULL
  directory: __dirname + '/locales',
  defaultLocale: 'nl'
});

app.use(i18n.init);

// you don't need that middleware with a proper configuration of i18n
// app.use(function(req, res, next) {
//   console.log(i18n);
//   if (req.query.lang != undefined && i18n.locales.indexOf(req.query.lang) >= 0) {
//     i18n.setLocale(req.query.lang);
//   } else {
//     i18n.setLocale(i18n.defaultLocale);
//   }
//   next();
// });

app.get('/home', function(req, res, next){

  /**
   * req.__() will lookup 'Hello World' and add it if missing
   * or return it's translated string form a locale file named
   * nl.json or fr.json.
   *
   * i18n.init takes care of setting locale according to cookie 
   * and query parameter in precedence of:
   *
   * 1. HTTP-Headers, fallback to
   * 2. cookie, fallback to
   * 3. query
   *
   * that way you might for exampple overwrite any language cookie 
   * with a query parameter.
   */

  res.send('<body>' + req.__('Hello World') + '</body>');
})
```

so assuming a req.cookie "gmlang" with "nl" as value you'll get 

GET /home => Hallo Wereld

but..

GET /home?lang=fr => Bonjour le monde

**Comment by goowikns** [comment]
When trying your example, I get following error when using the debug feature in the i18n configure function:

```
debug will use C:\Users\...\project\locales\nl.j
son
debug read C:\Users\...\project\locales\nl.json
for locale: nl
error unable to parse locales from file (maybe C:\Users\...\project\locales\nl.json is empty or invalid json?):
warn WARN: Locale nl couldn't be read - check the context of the call to $__
. Using nl (default) as current locale
debug will use C:\Users\...\project\locales\nl.j
son
debug read C:\Users\...\project\locales\nl.json
for locale: nl
error unable to parse locales from file (maybe C:\Users\...\project\locales\nl.json is empty or invalid json?):

```

**Comment by mashpie** [comment]
nothing more to say than:

```
error unable to parse locales from file (maybe C:\Users\...\project\locales\nl.json is empty or invalid json?):
```

**Comment by goowikns** [comment]
Problem is, it isn't empty:

```
{
  //form signup
  //labels
  "f-firstname": "Voornaam",
  "f-lastname": "Naam",
  "f-function": "Functie binnen de instelling",
  "f-company": "Instelling benaming",
  "f-company-n": "Ondernemingsnummer",
  "f-branch-n": "Vestigingsnummer",
  "f-member-organisation": "Lid van organiserende vereniging(en)",
  "f-street-and-n": "Straat & nummer",
  "f-postcode-n": "Postcode",
  "f-city": "Gemeente",
  "f-work-n": "Telefoon werk",
  "f-mobile-n": "Telefoon mobiel",
  "f-desired-username": "Gewenste gebruikersnaam",
  //placeholders
  "f-p-firstname": "Voornaam",
  "f-p-lastname": "Naam",
  "f-p-function": "Functie",
  "f-p-company": "Instelling",
  "f-p-company-n": "Ondernemings n°",
  "f-p-branch-n": "Vestigings n°",
  "f-p-member-organisation": "",
  "f-p-street-and-n": "Straat & nummer",
  "f-p-postcode-n": "Postcode",
  "f-p-city": "Gemeente",
  "f-p-work-n": "Telefoon",
  "f-p-mobile-n": "Mobiel",
  "f-p-desired-username": "Gebruikersnaam",

  //form login
  "f-username": "Gebruikersnaam",
  "f-email": "E-mail",
  "f-password": "Paswoord",
  "f-password-c": "Paswoord confirmatie"
}
```

**Comment by mashpie** [comment]
but invalid! Nativ JSON has no support for comments. Remove you comments and check again.

**Comment by goowikns** [comment]
I feel so dumb :(
I have no idea why I didn't check it first. Sorry about that !

**Comment by mashpie** [comment]
no worries :) Hoped to support json5 sooner

**Comment by shivangidas** [comment]
I got this error when I tried to switch from localhost to my IP address

Initial code
```
app.listen(8080);
console.log("Magic happens here : http://localhost:8080");
```
New code
```
var server = app.listen(4000, "192.168.10.244", function () {

  var host = server.address().address
  var port = server.address().port

  console.log("Magic happens here http://%s:%s", host, port)

});
```


Rest of my code
```
i18n.configure({
locales: ['en', 'zh', 'spa'],
directory: __dirname + '/locales',
defaultLocale: 'en',
cookie: 'i18n'
});
app.use(cookieParser("i18n_demo"));

app.use(session({
    secret: "i18n_demo",
    resave: true,
    saveUninitialized: true,
    cookie: { maxAge: 60000 }
}));

app.use(i18n.init);

app.get('/', function (req, res) {
    res.setLocale(req.cookies.i18n);
    res.render('main', {
    i18n: res
    })
});
```

**Comment by shivangidas** [comment]
The error

```
TypeError: Cannot set property 'locale' of undefined
    at ServerResponse.i18nSetLocale (C:\Users\Vinaya\Desktop\multilanguage\node_modules\i18n\i18n.js:408:25)
    at C:\Users\Vinaya\Desktop\multilanguage\server.js:64:9
    at Layer.handle [as handle_request] (C:\Users\Vinaya\Desktop\multilanguage\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Vinaya\Desktop\multilanguage\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\Vinaya\Desktop\multilanguage\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\Vinaya\Desktop\multilanguage\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\Vinaya\Desktop\multilanguage\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\Vinaya\Desktop\multilanguage\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\Vinaya\Desktop\multilanguage\node_modules\express\lib\router\index.js:275:10)
    at i18nInit (C:\Users\Vinaya\Desktop\multilanguage\node_modules\i18n\i18n.js:201:14)
```

**Comment by shivangidas** [comment]
Removing res.setLocale(req.cookies.i18n); worked, not sure how or why
