### ISSUE TITLE
__ is not defined error in EJS

### ISSUE THREAD

**Issue by eziya** [mashpie/i18n-node#287]
Hello, I got '__is not defined' error when I called ejs.render(). 
Any help would be appreciated.

Here's my code

```
var http = require('http');
var express = require('express');
var fs = require('fs');
var ejs = require('ejs');
var i18n = require('i18n');

i18n.configure({
    locales:['en','ko'],
    directory: __dirname + '/i18n'
});

var app = express();
app.use(express.favicon());
app.use(express.json());
app.use(express.static('public'));
app.use(express.bodyParser());
app.use(i18n.init);
app.use(app.router);

app.get('/', function (request, response) {
    fs.readFile('./public/view/index.ejs', 'utf8', function (err, data) {
        response.writeHead(200, {'Content-Type':'text/html'});
        response.end(ejs.render(data));
    });
});
```

EJS file (index.ejs)
```
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Temperature & Humidity Monitoring</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="/resources/css/bootstrap-datetimepicker.min.css" rel="stylesheet" media="screen">
</head>
<body>
<div class="container">
    <div class="jumbotron">
        <h1><%= __('title1') %></h1>
        <p><%= __('title2') %></p>
    </div>
</div>
</body>
</html>
```

Error message
```
ReferenceError: ejs:21
    19| <div class="container">
    20|     <div class="jumbotron">
 >> 21|         <h1><%= __('title1') %></h1>
    22|         <p><%= __('title2') %></p>
    23|     </div>
    24|

__ is not defined
    at eval (eval at compile (/home/ubuntu/nodejs/RestApp/node_modules/ejs/lib/ejs.js:491:12), <anonymous>:11:23)
    at returnedFn (/home/ubuntu/nodejs/RestApp/node_modules/ejs/lib/ejs.js:520:17)
    at Object.exports.render (/home/ubuntu/nodejs/RestApp/node_modules/ejs/lib/ejs.js:332:37)
    at /home/ubuntu/nodejs/RestApp/server.js:46:26
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
```

**Comment by mashpie** [comment]
obviously i18n is not bound to ejs.

```
response.end(ejs.render(data));
```

I bet it's bound to `response` only, thus `ejs` won't know any helpers. That should get fixed with express + ejs setup to use ejs as template angine, ie.:

```
// server.js
// load the things we need
var express = require('express');
var app = express();
var i18n = require('i18n');

// configure i18n
i18n.configure({
    locales:['en','ko'],
    directory: __dirname + '/i18n'
});

// initialise and bind to helpers
app.use(i18n.init);

// set the view engine to ejs
app.set('view engine', 'ejs');

// use res.render to load up an ejs view file

// index page 
app.get('/', function(req, res) {
    res.render('pages/index');
});

app.listen(8080);
console.log('8080 is the magic port');
```

**Comment by eziya** [comment]
Dear mashpie,

i appreciate your guidance. It solved my problem.

I added view engine codes as you mentioned
app.set('view engine', 'ejs');

and changed app.get call liked below,
```
app.get('/', function (request, response) {
    response.render('index');
});
```
