### ISSUE TITLE
Don't assume that if the provided folder doesn't exist the intention was to create it.

### ISSUE THREAD

**Issue by Izhaki** [mashpie/i18n-node#331]
## The code

```javascript
i18n.configure({
    locales: [ 'en' ],
    directory: path.join( __dirname, '/locales' ),
})
```

## The error

```
fs.js:922
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: EACCES: permission denied, mkdir '/locales'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:922:18)
    at write (/Volumes/Data/Development/Sites/nodemon-webpack-plugin/node_modules/i18n/i18n.js:1114:10)
    at read (/Volumes/Data/Development/Sites/nodemon-webpack-plugin/node_modules/i18n/i18n.js:1094:7)
    at /Volumes/Data/Development/Sites/nodemon-webpack-plugin/node_modules/i18n/i18n.js:157:9
    at Array.forEach (native)
    at Object.i18nConfigure [as configure] (/Volumes/Data/Development/Sites/nodemon-webpack-plugin/node_modules/i18n/i18n.js:156:19)
    at Object.<anonymous> (/Volumes/Data/Development/Sites/nodemon-webpack-plugin/test/dist/server.js:77:6)
    at Object.<anonymous> (/Volumes/Data/Development/Sites/nodemon-webpack-plugin/test/dist/server.js:93:30)
    at __webpack_require__ (/Volumes/Data/Development/Sites/nodemon-webpack-plugin/test/dist/server.js:20:30)
```

## My thoughts

Why the hell is it trying to `mkdir`???

## The dive

Into your code:

```javascript
  /**
   * try reading a file
   */
  var read = function(locale) {
    var localeFile = {},
      file = getStorageFilePath(locale);
    try {
      logDebug('read ' + file + ' for locale: ' + locale);
      localeFile = fs.readFileSync(file);
      try {
        // parsing filecontents to locales[locale]
        locales[locale] = JSON.parse(localeFile);
      } catch (parseError) {
        logError('unable to parse locales from file (maybe ' +
          file + ' is empty or invalid json?): ', parseError);
      }
    } catch (readError) {
      // unable to read, so intialize that file
      // locales[locale] are already set in memory, so no extra read required
      // or locales[locale] are empty, which initializes an empty locale.json file

      // since the current invalid locale could exist, we should back it up
      if (fs.existsSync(file)) {
        logDebug('backing up invalid locale ' + locale + ' to ' + file + '.invalid');
        fs.renameSync(file, file + '.invalid');
      }

      logDebug('initializing ' + file);
      write(locale);
    }
  };
```

## The problem

So it seems that if you provide an invalid path it tries create it?

It may make sense in a world where people get their paths wrong all the time...

## The solution

Webpack needs:

```javascript
    target: 'node',
    node: {
        __dirname: false,
        __filename: false,
    },
```

for `__dirname` to work. Problem solved.

## The plea

Consider the logic behind `read`. There is some good chance people will make mistakes there and assuming the original intent was to create something is rather dubious.

X

**Comment by mashpie** [comment]
...or change the appropiate settings:

```js
i18n.configure({
    locales: [ 'en' ],
    directory: path.join( __dirname, '/locales' ),

   // whether to write new locale information to disk - defaults to true
   updateFiles: false,
})
```

reference https://github.com/mashpie/i18n-node#list-of-all-configuration-options
